@startuml


class Parent {
}
note left: before

class Child1 {
+field
}

class Child2 {
+field
}

class Parent2 {
+field
}
note left: after

class Child3 {
}

class Child4 {
}

Parent <|-- Child1
Parent <|-- Child2

Parent2 <|-- Child3
Parent2 <|-- Child4

@enduml